create database latihan_act1;

use latihan_act1;

--1 
select EMP.ENAME, EMP.JOB, DEPT.LOC
from EMP, DEPT
where EMP.DEPTNO = 10 and EMP.DEPTNO = DEPT.DEPTNO

--2
select EMP.ENAME, EMP.JOB, EMP.SAL
FROM EMP
WHERE EMP.SAL > (SELECT AVG(SAL) FROM EMP WHERE EMP.JOB = 'ANALYST') AND EMP.JOB <> 'CLERK'

--3
select EMP.ENAME, EMP.EMPNO, EMP.JOB, DEPT.LOC, EMP.SAL
FROM EMP CROSS JOIN DEPT
WHERE EMP.ENAME = 'ALLEN'

--4
select EMP.EMPNO, EMP.ENAME, DEPT.DNAME, EMP.JOB, EMP.HIREDATE 
FROM EMP, DEPT 
WHERE EMP.SAL >= (SELECT EMP.SAL FROM EMP WHERE EMP.ENAME = 'BLAKE')
AND DEPT.DEPTNO = EMP.DEPTNO

--5 
select EMP.EMPNO, EMP.ENAME, DEPT.DNAME, EMP.SAL
FROM EMP LEFT OUTER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
AND SAL > 2000
ORDER BY EMP.SAL DESC

select EMP.EMPNO, EMP.ENAME, DEPT.DNAME, EMP.SAL
FROM EMP RIGHT OUTER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
AND SAL > 2000
ORDER BY EMP.SAL DESC